package com.cherrysoft.views;

import com.cherrysoft.views.imp.components.MatrixGridPanelParent;

import javax.swing.*;
import java.awt.*;

public class VistaSegundaMatriz extends JDialog {

  public VistaSegundaMatriz(Window owner) {
    super(owner);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jPanel1 = new javax.swing.JPanel();
    btnListo = new javax.swing.JButton();
    btnLimpiar = new javax.swing.JButton();
    panelMatriz = new MatrixGridPanelParent();
    jPanel3 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();

    setMinimumSize(new java.awt.Dimension(400, 300));

    btnListo.setText("Listo");
    jPanel1.add(btnListo);

    btnLimpiar.setText("Limpiar");
    jPanel1.add(btnLimpiar);

    getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

    panelMatriz.setBorder(javax.swing.BorderFactory.createTitledBorder("Segunda Matriz"));
    panelMatriz.setLayout(new java.awt.BorderLayout());
    getContentPane().add(panelMatriz, java.awt.BorderLayout.CENTER);

    jPanel3.setLayout(new java.awt.GridBagLayout());

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Si no establece un matriz válida, los cálculos se harán con la de entrada.");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1;
    gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
    jPanel3.add(jLabel1, gridBagConstraints);

    getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  public JButton getBtnLimpiar() {
    return btnLimpiar;
  }

  public JButton getBtnListo() {
    return btnListo;
  }

  public MatrixGridPanelParent getPanelMatriz() {
    return panelMatriz;
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnLimpiar;
  private javax.swing.JButton btnListo;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel3;
  private MatrixGridPanelParent panelMatriz;
  // End of variables declaration//GEN-END:variables
}
