package com.sw.view;

import com.sw.controller.LayoutManagerAdapter;
import java.awt.Container;
import javax.swing.JTextField;

/**
 *
 * @author Mohammed
 */
public final class MatrixDesign extends javax.swing.JPanel
{

    private int ladoMatriz;

    public MatrixDesign(int ladoMatriz, String title)
    {

        this.ladoMatriz = ladoMatriz;

        setName(title);

        entradasMatriz = new JTextField[ladoMatriz][ladoMatriz];

        initComponents();

        setLayout(new Diseno(ladoMatriz));

        anadirEntradasMatriz();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, getName(), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 14))); // NOI18N
        setToolTipText(getToolTipText());
        setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("null");
    }// </editor-fold>//GEN-END:initComponents

    private void anadirEntradasMatriz()
    {
        for (JTextField[] fila : entradasMatriz)
            for (int j = 0; j < entradasMatriz[0].length; j++)
            {
                fila[j] = new JTextField();
                add(fila[j]);

            }

    }

    public JTextField[][] getEntradasMatriz()
    {
        return entradasMatriz;
    }

    public int getLadoMatriz()
    {
        return ladoMatriz;
    }

    private class Diseno extends LayoutManagerAdapter
    {

        private int ladoMatriz;

        public Diseno(int ladoMatriz)
        {
            this.ladoMatriz = ladoMatriz;
        }

        @Override
        public void layoutContainer(Container parent)
        {
            int x = 25, y = 25;

            for (int i = 0; i < parent.getComponentCount(); i++)
            {

                parent.getComponent(i).setBounds(x, y, 50, 25);

                x += 55;

                if ((i + 1) % ladoMatriz == 0)
                {

                    y += 30;
                    x = 25;

                }

            }

        }

    }

    private JTextField[][] entradasMatriz;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
