package com.sw.view;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

/**
 *
 * @author Nicolás
 */
public class VistaPrincipal extends javax.swing.JFrame
{

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal()
    {
        initLookAndFeel();
        initComponents();
    }

    private void initLookAndFeel()
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels())
                if ("Windows".equals(info.getName()))
                {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex)
        {
            System.out.println(ex.getMessage());
        }
        //</editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        GridBagConstraints gridBagConstraints;

        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        btnDefinirOrden = new JButton();
        jLabel3 = new JLabel();
        jPanel7 = new JPanel();
        jPanel8 = new JPanel();
        btnCalcular = new JButton();
        jPanel9 = new JPanel();
        btnLimpiar = new JButton();
        btnSetSegundaMatriz = new JButton();
        ckbHabilitarSegundaMatriz = new JCheckBox();
        jPanel10 = new JPanel();
        jLabel4 = new JLabel();
        txtDeterminante = new JTextField();
        spOrdenMatriz = new JSpinner();
        spEscalar = new JSpinner();
        panelMatriz = new JPanel();
        panelSumaOtraMatriz = new JPanel();
        panelMultiOtraMatriz = new JPanel();
        panelMultiEscalar = new JPanel();
        panelInversaMatriz = new JPanel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new Dimension(800, 710));
        setPreferredSize(new Dimension(800, 710));
        getContentPane().setLayout(new GridLayout(3, 2));

        jPanel1.setBorder(BorderFactory.createTitledBorder("Entrada"));
        jPanel1.setLayout(new GridBagLayout());

        jLabel1.setFont(new Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setText("Calculadora de matrices");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(3, 3, 3, 3);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel2.setText("Orden de la matriz:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(1, 1, 1, 1);
        jPanel1.add(jLabel2, gridBagConstraints);

        btnDefinirOrden.setText("Definir");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(1, 1, 1, 1);
        jPanel1.add(btnDefinirOrden, gridBagConstraints);

        jLabel3.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel3.setText("Define un escalar:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(1, 1, 1, 1);
        jPanel1.add(jLabel3, gridBagConstraints);

        jPanel7.setLayout(new BorderLayout());

        jPanel8.setLayout(new FlowLayout(FlowLayout.RIGHT));

        btnCalcular.setText("Calcular");
        jPanel8.add(btnCalcular);

        jPanel7.add(jPanel8, BorderLayout.SOUTH);

        jPanel9.setLayout(new GridBagLayout());

        btnLimpiar.setText("Limpiar todos los campos");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(0, 1, 1, 1);
        jPanel9.add(btnLimpiar, gridBagConstraints);

        btnSetSegundaMatriz.setText("Establecer una segunda matriz");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new Insets(5, 1, 0, 1);
        jPanel9.add(btnSetSegundaMatriz, gridBagConstraints);

        ckbHabilitarSegundaMatriz.setSelected(true);
        ckbHabilitarSegundaMatriz.setText("Habilitar segunda matriz");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        jPanel9.add(ckbHabilitarSegundaMatriz, gridBagConstraints);

        GroupLayout jPanel10Layout = new GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(jPanel10Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(jPanel10Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.1;
        jPanel9.add(jPanel10, gridBagConstraints);

        jPanel7.add(jPanel9, BorderLayout.CENTER);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(jPanel7, gridBagConstraints);

        jLabel4.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel4.setText("Determinante:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(1, 1, 1, 1);
        jPanel1.add(jLabel4, gridBagConstraints);

        txtDeterminante.setEditable(false);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(1, 1, 1, 1);
        jPanel1.add(txtDeterminante, gridBagConstraints);

        spOrdenMatriz.setModel(new SpinnerNumberModel(3, 3, 10, 1));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(1, 1, 1, 1);
        jPanel1.add(spOrdenMatriz, gridBagConstraints);

        spEscalar.setModel(new SpinnerNumberModel(1.0d, null, null, 1.0d));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(1, 1, 1, 1);
        jPanel1.add(spEscalar, gridBagConstraints);

        getContentPane().add(jPanel1);

        panelMatriz.setBorder(BorderFactory.createTitledBorder("Matriz"));
        panelMatriz.setLayout(new BorderLayout());
        getContentPane().add(panelMatriz);

        panelSumaOtraMatriz.setBorder(BorderFactory.createTitledBorder("Suma con otra matriz"));
        panelSumaOtraMatriz.setLayout(new BorderLayout());
        getContentPane().add(panelSumaOtraMatriz);

        panelMultiOtraMatriz.setBorder(BorderFactory.createTitledBorder("Multiplicación con otra matriz"));
        panelMultiOtraMatriz.setLayout(new BorderLayout());
        getContentPane().add(panelMultiOtraMatriz);

        panelMultiEscalar.setBorder(BorderFactory.createTitledBorder("Multiplicación por escalar"));
        panelMultiEscalar.setLayout(new BorderLayout());
        getContentPane().add(panelMultiEscalar);

        panelInversaMatriz.setBorder(BorderFactory.createTitledBorder("Inversa de la matriz"));
        panelInversaMatriz.setLayout(new BorderLayout());
        getContentPane().add(panelInversaMatriz);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnCalcular()
    {
        return btnCalcular;
    }

    public JButton getBtnDefinirOrden()
    {
        return btnDefinirOrden;
    }

    public JButton getBtnLimpiar()
    {
        return btnLimpiar;
    }

    public JButton getBtnSetSegundaMatriz()
    {
        return btnSetSegundaMatriz;
    }

    public JPanel getPanelInversaMatriz()
    {
        return panelInversaMatriz;
    }

    public JPanel getPanelMatriz()
    {
        return panelMatriz;
    }

    public JPanel getPanelMultiEscalar()
    {
        return panelMultiEscalar;
    }

    public JPanel getPanelMultiOtraMatriz()
    {
        return panelMultiOtraMatriz;
    }

    public JPanel getPanelSumaOtraMatriz()
    {
        return panelSumaOtraMatriz;
    }

    public JSpinner getSpEscalar()
    {
        return spEscalar;
    }

    public JSpinner getSpOrdenMatriz()
    {
        return spOrdenMatriz;
    }

    public JTextField getTxtDeterminante()
    {
        return txtDeterminante;
    }

    public JCheckBox getCkbHabilitarSegundaMatriz()
    {
        return ckbHabilitarSegundaMatriz;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnCalcular;
    private JButton btnDefinirOrden;
    private JButton btnLimpiar;
    private JButton btnSetSegundaMatriz;
    private JCheckBox ckbHabilitarSegundaMatriz;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JPanel jPanel1;
    private JPanel jPanel10;
    private JPanel jPanel7;
    private JPanel jPanel8;
    private JPanel jPanel9;
    private JPanel panelInversaMatriz;
    private JPanel panelMatriz;
    private JPanel panelMultiEscalar;
    private JPanel panelMultiOtraMatriz;
    private JPanel panelSumaOtraMatriz;
    private JSpinner spEscalar;
    private JSpinner spOrdenMatriz;
    private JTextField txtDeterminante;
    // End of variables declaration//GEN-END:variables
}
